INSERT Genre (GenreID, Genre) VALUES (1, N'Western');
INSERT Genre (GenreID, Genre) VALUES (2, N'Drama');
INSERT Genre (GenreID, Genre) VALUES (3, N'Science Fiction');
INSERT Genre (GenreID, Genre) VALUES (4, N'Action');
INSERT Genre (GenreID, Genre) VALUES (5, N'War');
INSERT Genre (GenreID, Genre) VALUES (6, N'Romance');
INSERT Genre (GenreID, Genre) VALUES (7, N'Comedy');
INSERT Genre (GenreID, Genre) VALUES (8, N'Adventure');
INSERT Genre (GenreID, Genre) VALUES (9, N'Thriller');
INSERT Genre (GenreID, Genre) VALUES (10, N'Horror');
INSERT Genre (GenreID, Genre) VALUES (11, N'Animation');
INSERT Genre (GenreID, Genre) VALUES (12, N'Fantasy');
INSERT Genre (GenreID, Genre) VALUES (13, N'History');
INSERT Genre (GenreID, Genre) VALUES (14, N'Crime');
INSERT Genre (GenreID, Genre) VALUES (17, N'Martial Arts');
INSERT Genre (GenreID, Genre) VALUES (18, N'Mystery');
INSERT Genre (GenreID, Genre) VALUES (19, N'Biography');
INSERT Genre (GenreID, Genre) VALUES (20, N'Musical');
INSERT Genre (GenreID, Genre) VALUES (22, N'Sport');
INSERT Genre (GenreID, Genre) VALUES (24, N'Documentary');
INSERT Genre (GenreID, Genre) VALUES (25, N'Disaster');
INSERT Genre (GenreID, Genre) VALUES (26, N'Family');
INSERT Genre (GenreID, Genre) VALUES (27, N'Romantic Comedy');
INSERT Genre (GenreID, Genre) VALUES (28, N'Awful');
