INSERT Studio (StudioID, Studio) VALUES (1, N'Universal Pictures');
INSERT Studio (StudioID, Studio) VALUES (2, N'Paramount Pictures');
INSERT Studio (StudioID, Studio) VALUES (3, N'Walt Disney Pictures');
INSERT Studio (StudioID, Studio) VALUES (4, N'20th Century Fox');
INSERT Studio (StudioID, Studio) VALUES (5, N'Columbia Pictures');
INSERT Studio (StudioID, Studio) VALUES (6, N'Warner Bros. Pictures');
INSERT Studio (StudioID, Studio) VALUES (7, N'Touchstone Pictures');
INSERT Studio (StudioID, Studio) VALUES (8, N'Dreamworks');
INSERT Studio (StudioID, Studio) VALUES (9, N'ImageMovers');
INSERT Studio (StudioID, Studio) VALUES (10, N'Pixar Animation Studios');
INSERT Studio (StudioID, Studio) VALUES (11, N'Metro-ldwyn-Mayer');
INSERT Studio (StudioID, Studio) VALUES (12, N'Chris Lee Productions');
INSERT Studio (StudioID, Studio) VALUES (13, N'Lucasfilm');
INSERT Studio (StudioID, Studio) VALUES (14, N'New Line Cinema');
INSERT Studio (StudioID, Studio) VALUES (15, N'Carolco Pictures');
INSERT Studio (StudioID, Studio) VALUES (16, N'Miramax Films');
INSERT Studio (StudioID, Studio) VALUES (17, N'Jerry Bruckheimer Films');
INSERT Studio (StudioID, Studio) VALUES (18, N'Gaumont');
INSERT Studio (StudioID, Studio) VALUES (19, N'Revolution Studios');
INSERT Studio (StudioID, Studio) VALUES (20, N'Imagine Entertainment');
INSERT Studio (StudioID, Studio) VALUES (21, N'Morgan Creek Productions');
INSERT Studio (StudioID, Studio) VALUES (22, N'United Artists');
INSERT Studio (StudioID, Studio) VALUES (23, N'Dimension Films');
INSERT Studio (StudioID, Studio) VALUES (24, N'Braveworld Productions');
INSERT Studio (StudioID, Studio) VALUES (25, N'Icon Productions');
INSERT Studio (StudioID, Studio) VALUES (26, N'Carolina Bank');
INSERT Studio (StudioID, Studio) VALUES (27, N'Tig Productions');
INSERT Studio (StudioID, Studio) VALUES (28, N'Dune Entertainment');
INSERT Studio (StudioID, Studio) VALUES (29, N'Beijing New Picture Film Co.');
INSERT Studio (StudioID, Studio) VALUES (30, N'Big Talk Productions');
INSERT Studio (StudioID, Studio) VALUES (31, N'The Malpaso Company');
INSERT Studio (StudioID, Studio) VALUES (32, N'British Film Council');
INSERT Studio (StudioID, Studio) VALUES (33, N'Channel Four Films');
INSERT Studio (StudioID, Studio) VALUES (34, N'Constantin Film');
INSERT Studio (StudioID, Studio) VALUES (35, N'Bavaria Film');
INSERT Studio (StudioID, Studio) VALUES (36, N'Bayerischer Rundfunk');
INSERT Studio (StudioID, Studio) VALUES (37, N'RKO Radio Pictures');
INSERT Studio (StudioID, Studio) VALUES (38, N'Toho Company');
INSERT Studio (StudioID, Studio) VALUES (39, N'Kathbur Pictures');
INSERT Studio (StudioID, Studio) VALUES (40, N'Avalon Studios');
INSERT Studio (StudioID, Studio) VALUES (41, N'Amblin Entertainment');
INSERT Studio (StudioID, Studio) VALUES (42, N'WingNut Films');
INSERT Studio (StudioID, Studio) VALUES (43, N'Legendary Pictures');
INSERT Studio (StudioID, Studio) VALUES (44, N'Spyglass Entertainment');
INSERT Studio (StudioID, Studio) VALUES (45, N'rdon Company');
INSERT Studio (StudioID, Studio) VALUES (46, N'di Bonaventura Pictures');
INSERT Studio (StudioID, Studio) VALUES (47, N'Heyday Films');
INSERT Studio (StudioID, Studio) VALUES (48, N'Shangri-La Entertainment');
INSERT Studio (StudioID, Studio) VALUES (49, N'Village Roadshow Pictures');
INSERT Studio (StudioID, Studio) VALUES (50, N'Helena Productions');
INSERT Studio (StudioID, Studio) VALUES (51, N'Eon Productions');
INSERT Studio (StudioID, Studio) VALUES (52, N'Silver Pictures');
INSERT Studio (StudioID, Studio) VALUES (53, N'Marvel Entertainment');
INSERT Studio (StudioID, Studio) VALUES (54, N'Original Film');
INSERT Studio (StudioID, Studio) VALUES (55, N'Square Pictures');
INSERT Studio (StudioID, Studio) VALUES (56, N'The Kennedy Marshall Company');
INSERT Studio (StudioID, Studio) VALUES (57, N'Centropolis Entertainment');
INSERT Studio (StudioID, Studio) VALUES (58, N'Radar Pictures');
INSERT Studio (StudioID, Studio) VALUES (59, N'Cruise Wagner Productions');
INSERT Studio (StudioID, Studio) VALUES (60, N'Lion Rock Productions');
INSERT Studio (StudioID, Studio) VALUES (61, N'Jerry Weintraub Productions');
INSERT Studio (StudioID, Studio) VALUES (62, N'Cheyenne Enterprises');
INSERT Studio (StudioID, Studio) VALUES (63, N'Walden Media');
INSERT Studio (StudioID, Studio) VALUES (64, N'Scott Free Productions');
INSERT Studio (StudioID, Studio) VALUES (65, N'Regency Enterprises');
INSERT Studio (StudioID, Studio) VALUES (66, N'Forward Pass');
INSERT Studio (StudioID, Studio) VALUES (67, N'Peters Entertainment');
INSERT Studio (StudioID, Studio) VALUES (68, N'Davis Entertainment');
INSERT Studio (StudioID, Studio) VALUES (69, N'The Bedford Falls Company');
INSERT Studio (StudioID, Studio) VALUES (70, N'Lightstorm Entertainment');
INSERT Studio (StudioID, Studio) VALUES (71, N'Roger Birnbaum Productions');
INSERT Studio (StudioID, Studio) VALUES (72, N'Cinergi Pictures');
INSERT Studio (StudioID, Studio) VALUES (73, N'The Zanuck Company');
INSERT Studio (StudioID, Studio) VALUES (74, N'Strike Entertainment');
INSERT Studio (StudioID, Studio) VALUES (75, N'Hollywood Pictures');
INSERT Studio (StudioID, Studio) VALUES (76, N'Apatow Productions');
INSERT Studio (StudioID, Studio) VALUES (77, N'Gracie Films');
INSERT Studio (StudioID, Studio) VALUES (78, N'Mandalay Pictures');
INSERT Studio (StudioID, Studio) VALUES (79, N'Fox 2000 Pictures');
INSERT Studio (StudioID, Studio) VALUES (80, N'Millennium Films');
INSERT Studio (StudioID, Studio) VALUES (81, N'Scott Rudin Productions');
INSERT Studio (StudioID, Studio) VALUES (82, N'Weed Road Pictures');
INSERT Studio (StudioID, Studio) VALUES (83, N'Dovemead');
INSERT Studio (StudioID, Studio) VALUES (84, N'A Band Apart');
INSERT Studio (StudioID, Studio) VALUES (85, N'Brandywine Productions');
INSERT Studio (StudioID, Studio) VALUES (86, N'Pacific Data Images');
INSERT Studio (StudioID, Studio) VALUES (87, N'Tapestry Films');
INSERT Studio (StudioID, Studio) VALUES (88, N'Taliafilm');
INSERT Studio (StudioID, Studio) VALUES (89, N'Jersey Films');
INSERT Studio (StudioID, Studio) VALUES (90, N'Virtual Studios');
INSERT Studio (StudioID, Studio) VALUES (91, N'Lakeshore Entertainment');
INSERT Studio (StudioID, Studio) VALUES (92, N'Mace Neufeld Productions');
INSERT Studio (StudioID, Studio) VALUES (93, N'Black Rhino');
INSERT Studio (StudioID, Studio) VALUES (94, N'The Ladd Company');
INSERT Studio (StudioID, Studio) VALUES (95, N'Republic Pictures');
INSERT Studio (StudioID, Studio) VALUES (96, N'Dino De Laurentiis Corporation');
INSERT Studio (StudioID, Studio) VALUES (97, N'ldcrest Films');
INSERT Studio (StudioID, Studio) VALUES (98, N'Jinks/Cohen Company');
INSERT Studio (StudioID, Studio) VALUES (99, N'EDKO Films');
INSERT Studio (StudioID, Studio) VALUES (100, N'River Road Entertainment');
INSERT Studio (StudioID, Studio) VALUES (101, N'Newmarket Capital Group');
INSERT Studio (StudioID, Studio) VALUES (102, N'UGC');
INSERT Studio (StudioID, Studio) VALUES (103, N'lden Harvest');
INSERT Studio (StudioID, Studio) VALUES (104, N'Polygram Filmed Entertainment');
INSERT Studio (StudioID, Studio) VALUES (105, N'2929 Entertainment');
INSERT Studio (StudioID, Studio) VALUES (106, N'Hemdale');
INSERT Studio (StudioID, Studio) VALUES (107, N'Bad Hat Harry Productions');
INSERT Studio (StudioID, Studio) VALUES (108, N'Summit Entertainment');
INSERT Studio (StudioID, Studio) VALUES (109, N'Channel One Russia');
INSERT Studio (StudioID, Studio) VALUES (110, N'Live Entertainment');
INSERT Studio (StudioID, Studio) VALUES (111, N'The Con');
INSERT Studio (StudioID, Studio) VALUES (112, N'Greenwich Film Productions');
INSERT Studio (StudioID, Studio) VALUES (113, N'DNA Films');
INSERT Studio (StudioID, Studio) VALUES (114, N'Communicado Productions');
INSERT Studio (StudioID, Studio) VALUES (115, N'Aardman Animations');
INSERT Studio (StudioID, Studio) VALUES (116, N'Jesse L. Lasky Feature Play Company');
INSERT Studio (StudioID, Studio) VALUES (117, N'Thanhouser Film Corporation');
INSERT Studio (StudioID, Studio) VALUES (118, N'Fox Film Corporation');
INSERT Studio (StudioID, Studio) VALUES (119, N'Keystone Film Company');
INSERT Studio (StudioID, Studio) VALUES (120, N'Color Force');
INSERT Studio (StudioID, Studio) VALUES (121, N'Famous Players Film Company');
INSERT Studio (StudioID, Studio) VALUES (122, N'Deutsche Bioscop');
INSERT Studio (StudioID, Studio) VALUES (123, N'Chernin Entertainment');
INSERT Studio (StudioID, Studio) VALUES (124, N'Illumination Entertainment');
INSERT Studio (StudioID, Studio) VALUES (125, N'Temple Hill Entertainment');
INSERT Studio (StudioID, Studio) VALUES (126, N'Bad Robot Productions');
INSERT Studio (StudioID, Studio) VALUES (127, N'Sony Pictures');
INSERT Studio (StudioID, Studio) VALUES (128, N'Relativity Media');
INSERT Studio (StudioID, Studio) VALUES (129, N'Playtone Entertainment');
INSERT Studio (StudioID, Studio) VALUES (130, N'Overbrook Entertainment');
INSERT Studio (StudioID, Studio) VALUES (131, N'Tribeca Productions');
INSERT Studio (StudioID, Studio) VALUES (132, N'Intermedia');
INSERT Studio (StudioID, Studio) VALUES (133, N'DC Entertainment');
INSERT Studio (StudioID, Studio) VALUES (134, N'China Film Group');
INSERT Studio (StudioID, Studio) VALUES (135, N'ld Circle Films');
INSERT Studio (StudioID, Studio) VALUES (136, N'O2 Filmes');
INSERT Studio (StudioID, Studio) VALUES (137, N'Alphaville Films');
INSERT Studio (StudioID, Studio) VALUES (138, N'Eric''s Boy');
INSERT Studio (StudioID, Studio) VALUES (139, N'Zucker Brothers Productions');
INSERT Studio (StudioID, Studio) VALUES (140, N'Kopelson Entertainment');
INSERT Studio (StudioID, Studio) VALUES (141, N'Interscope Communications');
INSERT Studio (StudioID, Studio) VALUES (142, N'Dark Horse Entertainment');
INSERT Studio (StudioID, Studio) VALUES (143, N'Mark rdon Productions');
INSERT Studio (StudioID, Studio) VALUES (144, N'Motion Picture Corporation of America');
INSERT Studio (StudioID, Studio) VALUES (145, N'Geffen Pictures');
INSERT Studio (StudioID, Studio) VALUES (146, N'Blue Wolf Productions');
INSERT Studio (StudioID, Studio) VALUES (147, N'TriStar Pictures');
INSERT Studio (StudioID, Studio) VALUES (148, N'Hughes Entertainment');
INSERT Studio (StudioID, Studio) VALUES (149, N'Castle Rock Entertainment');
INSERT Studio (StudioID, Studio) VALUES (150, N'Strong Heart/Demme Production');
INSERT Studio (StudioID, Studio) VALUES (151, N'Orion Pictures');
INSERT Studio (StudioID, Studio) VALUES (152, N'Eddie Murphy Productions');
INSERT Studio (StudioID, Studio) VALUES (153, N'Rastar');
INSERT Studio (StudioID, Studio) VALUES (154, N'Kennedy Miller');
INSERT Studio (StudioID, Studio) VALUES (155, N'Rimfire Films');
INSERT Studio (StudioID, Studio) VALUES (156, N'Mirage Studios');
INSERT Studio (StudioID, Studio) VALUES (157, N'Lorimar Productions');
INSERT Studio (StudioID, Studio) VALUES (158, N'Astral Media');
INSERT Studio (StudioID, Studio) VALUES (159, N'Handmade Films');
INSERT Studio (StudioID, Studio) VALUES (160, N'Zoetrope Studios');
INSERT Studio (StudioID, Studio) VALUES (161, N'Henson Associates');
INSERT Studio (StudioID, Studio) VALUES (162, N'Laurel Group');
INSERT Studio (StudioID, Studio) VALUES (163, N'Sellers-Edwards Productions');
INSERT Studio (StudioID, Studio) VALUES (164, N'EMI Films');
INSERT Studio (StudioID, Studio) VALUES (165, N'Joseph E. Levine Productions');
INSERT Studio (StudioID, Studio) VALUES (166, N'Allied Artists');
INSERT Studio (StudioID, Studio) VALUES (167, N'The Mirisch Production Company');
INSERT Studio (StudioID, Studio) VALUES (168, N'Hawk Films');
INSERT Studio (StudioID, Studio) VALUES (169, N'Alfred J. Hitchcock Productions');
INSERT Studio (StudioID, Studio) VALUES (170, N'Horizon Pictures');
INSERT Studio (StudioID, Studio) VALUES (171, N'Samuel Bronston Productions');
INSERT Studio (StudioID, Studio) VALUES (172, N'Pathe');
INSERT Studio (StudioID, Studio) VALUES (173, N'Bryna Productions');
INSERT Studio (StudioID, Studio) VALUES (174, N'Shamley Productions');
INSERT Studio (StudioID, Studio) VALUES (175, N'Selznick International Pictures');
INSERT Studio (StudioID, Studio) VALUES (176, N'Bing Crosby Productions');
INSERT Studio (StudioID, Studio) VALUES (177, N'Romulus Films');
INSERT Studio (StudioID, Studio) VALUES (178, N'Transatlantic Pictures');
INSERT Studio (StudioID, Studio) VALUES (179, N'Cosmopolitan Productions');
INSERT Studio (StudioID, Studio) VALUES (180, N'Charles Chaplin Film Corporation');
INSERT Studio (StudioID, Studio) VALUES (181, N'Seven Arts Productions');
INSERT Studio (StudioID, Studio) VALUES (182, N'Mercury Productions');
INSERT Studio (StudioID, Studio) VALUES (183, N'Universum Film');
INSERT Studio (StudioID, Studio) VALUES (184, N'London Film Productions');
INSERT Studio (StudioID, Studio) VALUES (185, N'Liberty Films');
INSERT Studio (StudioID, Studio) VALUES (186, N'Cineguild');
INSERT Studio (StudioID, Studio) VALUES (187, N'Ortus Films');
INSERT Studio (StudioID, Studio) VALUES (188, N'Two Cities Films');
INSERT Studio (StudioID, Studio) VALUES (189, N'Sierra Pictures');
INSERT Studio (StudioID, Studio) VALUES (190, N'Python (Monty) Pictures');
INSERT Studio (StudioID, Studio) VALUES (191, N'Seasonal Film Corporation');
INSERT Studio (StudioID, Studio) VALUES (192, N'Lo Wei Motion Picture Company');
INSERT Studio (StudioID, Studio) VALUES (193, N'od Year Movie Company');
INSERT Studio (StudioID, Studio) VALUES (194, N'Eastern Productions');
INSERT Studio (StudioID, Studio) VALUES (195, N'StudioCanal');
INSERT Studio (StudioID, Studio) VALUES (196, N'EuropaCorp');
INSERT Studio (StudioID, Studio) VALUES (197, N'We Pictures');
INSERT Studio (StudioID, Studio) VALUES (198, N'Cinema City');
INSERT Studio (StudioID, Studio) VALUES (199, N'lden Princess Film Production Limited');
INSERT Studio (StudioID, Studio) VALUES (200, N'Film Workshop');
INSERT Studio (StudioID, Studio) VALUES (201, N'PT. Merantau Films');
INSERT Studio (StudioID, Studio) VALUES (202, N'Baa-Ram-Ewe');
INSERT Studio (StudioID, Studio) VALUES (203, N'Sahamongkol Film International');
INSERT Studio (StudioID, Studio) VALUES (204, N'Dreams Salon Entertainment');
INSERT Studio (StudioID, Studio) VALUES (205, N'Daiei Film');
INSERT Studio (StudioID, Studio) VALUES (206, N'Moving Picture Company');
INSERT Studio (StudioID, Studio) VALUES (207, N'Omega Project');
INSERT Studio (StudioID, Studio) VALUES (208, N'Recorded Picture Company');
INSERT Studio (StudioID, Studio) VALUES (209, N'Asahi National Broadcasting Company');
INSERT Studio (StudioID, Studio) VALUES (210, N'Hasbro Studios');
INSERT Studio (StudioID, Studio) VALUES (211, N'Bandai Visual Company');
INSERT Studio (StudioID, Studio) VALUES (212, N'AM Associates');
INSERT Studio (StudioID, Studio) VALUES (213, N'Toei Kyoto');
INSERT Studio (StudioID, Studio) VALUES (214, N'Rankin/Bass Productions');
INSERT Studio (StudioID, Studio) VALUES (215, N'TV Tokyo');
INSERT Studio (StudioID, Studio) VALUES (216, N'Sedic International');
INSERT Studio (StudioID, Studio) VALUES (217, N'Eisei Gekijo');
INSERT Studio (StudioID, Studio) VALUES (218, N'La Petite Reine');
INSERT Studio (StudioID, Studio) VALUES (219, N'Rogue Pictures');
INSERT Studio (StudioID, Studio) VALUES (220, N'Why Not Productions');
INSERT Studio (StudioID, Studio) VALUES (221, N'FilmFour Productions');
INSERT Studio (StudioID, Studio) VALUES (222, N'BBC Films');
INSERT Studio (StudioID, Studio) VALUES (223, N'Baby Cow Productions');
INSERT Studio (StudioID, Studio) VALUES (224, N'Azari Media');
INSERT Studio (StudioID, Studio) VALUES (225, N'Blueprint Pictures');
INSERT Studio (StudioID, Studio) VALUES (226, N'Mythic International Entertainment');
INSERT Studio (StudioID, Studio) VALUES (228, N'Lionsgate');
INSERT Studio (StudioID, Studio) VALUES (229, N'Open Road Films');
INSERT Studio (StudioID, Studio) VALUES (230, N'Beacon Pictures');
INSERT Studio (StudioID, Studio) VALUES (231, N'White Mountain Films');
INSERT Studio (StudioID, Studio) VALUES (232, N'RAF Industires');
INSERT Studio (StudioID, Studio) VALUES (234, N'Plan B Entertainment');
INSERT Studio (StudioID, Studio) VALUES (235, N'Marv Films');
INSERT Studio (StudioID, Studio) VALUES (236, N'Tim Burton Productions');
INSERT Studio (StudioID, Studio) VALUES (237, N'Ealing Studios');
INSERT Studio (StudioID, Studio) VALUES (238, N'Kings Road Entertainment');
INSERT Studio (StudioID, Studio) VALUES (239, N'The Cannon Group');
INSERT Studio (StudioID, Studio) VALUES (240, N'Stanley Kubrick Productions');
INSERT Studio (StudioID, Studio) VALUES (241, N'Nikkatsu');
INSERT Studio (StudioID, Studio) VALUES (242, N'Act III Communications');
INSERT Studio (StudioID, Studio) VALUES (243, N'First Artists');
INSERT Studio (StudioID, Studio) VALUES (244, N'ABC Pictures');
INSERT Studio (StudioID, Studio) VALUES (245, N'View Askew Productions');
INSERT Studio (StudioID, Studio) VALUES (246, N'Verti Films');
INSERT Studio (StudioID, Studio) VALUES (247, N'FilmDistrict');
INSERT Studio (StudioID, Studio) VALUES (248, N'Embassy International');
INSERT Studio (StudioID, Studio) VALUES (249, N'Troublemaker Studios');
INSERT Studio (StudioID, Studio) VALUES (250, N'Double Feature Films');
INSERT Studio (StudioID, Studio) VALUES (251, N'Fuqua Films');
INSERT Studio (StudioID, Studio) VALUES (252, N'Artisan Entertainment');
INSERT Studio (StudioID, Studio) VALUES (253, N'Black Bear Pictures');
INSERT Studio (StudioID, Studio) VALUES (255, N'Yellow Bird');
INSERT Studio (StudioID, Studio) VALUES (256, N'Svensk Filmindustri');
INSERT Studio (StudioID, Studio) VALUES (257, N'This Is That');
INSERT Studio (StudioID, Studio) VALUES (258, N'The Weinstein Company');
INSERT Studio (StudioID, Studio) VALUES (259, N'Eli Tossell Film');
INSERT Studio (StudioID, Studio) VALUES (260, N'UK Film Council');
INSERT Studio (StudioID, Studio) VALUES (261, N'Hammer Film Productions');
INSERT Studio (StudioID, Studio) VALUES (262, N'Commonwealth United Entertainment');
INSERT Studio (StudioID, Studio) VALUES (263, N'BHE Films');
INSERT Studio (StudioID, Studio) VALUES (264, N'Cannon Productions');
INSERT Studio (StudioID, Studio) VALUES (265, N'Wise Owl Studios');
